### ISSUE TITLE
Implement the interface expected by the pool controller

### ISSUE THREAD

**Issue by d1ll0n** [indexed-finance/chainlink-integration#1]
The oracle should implement the interface expected by the new pool controller in sigma-core.

[Link to interface file](https://github.com/indexed-finance/sigma-core/blob/controller-update/contracts/interfaces/ICirculatingMarketCapOracle.sol)

```
  function getCirculatingMarketCap(address) external view returns (uint256);

  function getCirculatingMarketCaps(address[] calldata) external view returns (uint256[] memory);

  function updateCirculatingMarketCaps(address[] calldata) external;
  ```

**Comment by huy-springlabs** [comment]
Will take a look at this over the weekend.

**Comment by pumpchaser** [comment]
Ready for review https://github.com/indexed-finance/chainlink-integration/pull/2
